"""insert message

Revision ID: 7e977c924ad1
Revises: 
Create Date: 2021-07-03 11:37:05.449160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e977c924ad1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api',
    sa.Column('apiid', sa.Integer(), nullable=False),
    sa.Column('apiname', sa.String(length=120), nullable=True),
    sa.Column('requesttype', sa.Text(), nullable=True),
    sa.Column('apiurl', sa.Text(), nullable=True),
    sa.Column('apidata', sa.Text(), nullable=True),
    sa.Column('apiresponse', sa.Text(), nullable=True),
    sa.Column('statuscode', sa.Integer(), nullable=True),
    sa.Column('apireason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('apiid'),
    sa.UniqueConstraint('apiname')
    )
    op.create_table('stats',
    sa.Column('statid', sa.Integer(), nullable=False),
    sa.Column('apipass', sa.Integer(), nullable=True),
    sa.Column('apifail', sa.Integer(), nullable=True),
    sa.Column('apitotal', sa.Integer(), nullable=True),
    sa.Column('apisuccess', sa.Float(), nullable=True),
    sa.Column('apiwip', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('statid')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('about_me', sa.String(length=140), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('stats')
    op.drop_table('api')
    # ### end Alembic commands ###
