"""added new column names to Api table

Revision ID: d06b2acd5c9f
Revises: 
Create Date: 2021-06-21 11:42:40.916442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd06b2acd5c9f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api',
    sa.Column('apiid', sa.Integer(), nullable=False),
    sa.Column('apiname', sa.String(length=120), nullable=True),
    sa.Column('requesttype', sa.Text(), nullable=True),
    sa.Column('apiurl', sa.Text(), nullable=True),
    sa.Column('apiresponse', sa.Text(), nullable=True),
    sa.Column('statuscode', sa.Integer(), nullable=True),
    sa.Column('apireason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('apiid')
    )
    op.create_index(op.f('ix_api_apiname'), 'api', ['apiname'], unique=True)
    op.create_index(op.f('ix_api_apireason'), 'api', ['apireason'], unique=False)
    op.create_index(op.f('ix_api_apiresponse'), 'api', ['apiresponse'], unique=False)
    op.create_index(op.f('ix_api_apiurl'), 'api', ['apiurl'], unique=True)
    op.create_index(op.f('ix_api_requesttype'), 'api', ['requesttype'], unique=False)
    op.create_index(op.f('ix_api_statuscode'), 'api', ['statuscode'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('about_me', sa.String(length=140), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_api_statuscode'), table_name='api')
    op.drop_index(op.f('ix_api_requesttype'), table_name='api')
    op.drop_index(op.f('ix_api_apiurl'), table_name='api')
    op.drop_index(op.f('ix_api_apiresponse'), table_name='api')
    op.drop_index(op.f('ix_api_apireason'), table_name='api')
    op.drop_index(op.f('ix_api_apiname'), table_name='api')
    op.drop_table('api')
    # ### end Alembic commands ###
